const data=[
    {
        img:"https://i.ibb.co/MnsBR6x/asset-9.jpg",
        rating:3.8,
        price:1100,
        type:"MEHROON"
    },
    {
        img:"https://i.ibb.co/MgLx3YC/asset-31.jpg",
        rating:4.8,
        price:1400,
        type:"Femvy"
    },
    {
        img:"https://i.ibb.co/jz4ZG7W/asset-9.jpg",
        rating:2.5,
        price:1500,
        type:"PRISTINO"
    },
    {
        img:"https://i.ibb.co/2P07nrr/asset-44.jpg",
        rating:4.2,
        price:400,
        type:"VENUSY"
    },
    {
        img:"https://i.ibb.co/yRYDqCj/asset-13.jpg",
        rating:4.3,
        price:600,
        type:"ftDiva"
    },
    {
        img:"https://i.ibb.co/B6Cf7C1/asset-35.jpg",
        rating:4.7,
        price:7,
        type:"PankhudiSarees"
    },
    {
        img:"https://i.ibb.co/0mmSKj5/asset-37.jpg",
        rating:2.8,
        price:800,
        type:"AVDOM"
    },
    {
        img:"https://i.ibb.co/4Zv4wPV/asset-14.jpg",
        rating:5.2,
        price:300,
        type:"meaven tex"
    },
    {
        img:"https://i.ibb.co/q7Xv08Q/asset-41.jpg",
        rating:1.8,
        price:1100,
        type:"hesika"
    },
    {
        img:"https://i.ibb.co/0YFH67j/asset-22.jpg",
        rating:4.2,
        price:2200,
        type:"Klosia"
    },
    {
        img:"https://i.ibb.co/R9QFwQy/asset-20.jpg",
        rating:5.7,
        price:2800,
        type:"rtSuf Collection"
    },
    {
        img:"https://i.ibb.co/jLd8z06/asset-25.jpg",
        rating:7.4,
        price:900,
        type:"Balyx"
    },
    {
        img:"https://i.ibb.co/Vgds3PH/asset-41.jpg",
        rating:5.3,
        price:1500,
        type:"Kangopi fashion"
    },
    {
        img:"https://i.ibb.co/YpznM9P/asset-13.jpg",
        rating:2.2,
        price:2100,
        type:"Bunai Dhaga"
    },
    {
        img:"https://i.ibb.co/G7js6Gv/asset-43.jpg",
        rating:5.5,
        price:1700,
        type:"Madarwa"
    },
    {
        img:"https://i.ibb.co/BzJ59QR/asset-31.jpg",
        rating:2.4,
        price:1300,
        type:"shoecom"
    },
    {
        img:"https://i.ibb.co/1JxnJhD/asset-13.jpg",
        rating:4.9,
        price:900,
        type:"Divastri"
    },
    {
        img:"https://i.ibb.co/fqhBGJJ/asset-14.jpg",
        rating:5.6,
        price:350,
        type:"Rajovati"
    },
    {
        img:"https://i.ibb.co/BtG2P5t/asset-13.jpg",
        rating:5.6,
        price:500,
        type:"Rahi Trendz"
    },
    {
        img:"https://i.ibb.co/PQC0Kk1/asset-17.jpg",
        rating:5.4,
        price:250,
        type:"Absorbing"
    },
    {
        img:"https://i.ibb.co/kQhDjqv/asset-22.jpg",
        rating:4.8,
        price:250,
        type:"Q-Rious"
    },
    {
        img:"https://i.ibb.co/GkbJNfN/asset-43.jpg",
        rating:4.9,
        price:650,
        type:"swaggish"
    },
    {
        img:"https://i.ibb.co/DMrLcfV/asset-42.jpg",
        rating:4.1,
        price:300,
        type:"Toochki"
    },

]